# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8eb123001c5fed84f918fb2653a17ad32f451ac29b6b4fc8c41157b448d2adbb8c1c646c963847a9929ca2941c5b20efdc9bb3e0886367dcaf03e6b5f4781e40

test:
  secret_key_base: 8d55a384360a7349ca55d2954926a48925a8f59748b21d8a834db54e1b613b136bc598a4807e78e1f60ffc0780a521ee67a5d287b696b697fa7765e9d6bbebdc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
